/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splitwise;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import splitwise.dao.MemberDao;

/**
 *
 * @author adityahandadi
 */
public class AddMemberFrame extends MyFrame  {

    /**
     * Creates new form AddMemberFrame
     */
    private List<Member> memberList;
    public String group;
    
    public AddMemberFrame() {
        super();
        initComponents();
        
        memberList = new ArrayList();
        
        if(super.getGroupName() == null){
            System.out.println("No GroupName found ERROR");
        }
        else{
            //populate Members List
            populateMembers(memberList);
        }
    }
    
    public AddMemberFrame(String group) {
        super();
        initComponents();
        this.group = group;
        
        memberList = new ArrayList();
        
        if(this.group == null){
            System.out.println("No GroupName found ERROR");
        }
        else{
            //populate Members List
            populateMembers(memberList);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberTitle = new javax.swing.JPanel();
        titleOfMember = new javax.swing.JLabel();
        memberFormPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        memberName = new javax.swing.JTextField();
        memberEmail = new javax.swing.JTextField();
        addMember = new javax.swing.JButton();
        memberScrollPane = new java.awt.ScrollPane();
        membersList = new java.awt.TextArea();
        menBar = new javax.swing.JMenuBar();
        gotoLoginFrame = new javax.swing.JMenu();
        gotoExpFrame = new javax.swing.JMenu();
        gotoDashboard = new javax.swing.JMenu();
        gotoMember = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleOfMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleOfMember.setText("SPLITWISE - MEMBERS");

        javax.swing.GroupLayout memberTitleLayout = new javax.swing.GroupLayout(memberTitle);
        memberTitle.setLayout(memberTitleLayout);
        memberTitleLayout.setHorizontalGroup(
            memberTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleOfMember)
                .addContainerGap(631, Short.MAX_VALUE))
        );
        memberTitleLayout.setVerticalGroup(
            memberTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleOfMember)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name of the member: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("email Id of the member: ");

        memberName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberNameActionPerformed(evt);
            }
        });

        addMember.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addMember.setText("Add");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout memberFormPaneLayout = new javax.swing.GroupLayout(memberFormPane);
        memberFormPane.setLayout(memberFormPaneLayout);
        memberFormPaneLayout.setHorizontalGroup(
            memberFormPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberFormPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(memberFormPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memberFormPaneLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(memberEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(addMember))
                    .addGroup(memberFormPaneLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(37, 37, 37)
                        .addComponent(memberName, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        memberFormPaneLayout.setVerticalGroup(
            memberFormPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberFormPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(memberFormPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(memberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(memberFormPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(memberFormPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(memberFormPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(memberEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, memberFormPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addMember)
                        .addGap(14, 14, 14))))
        );

        memberScrollPane.add(membersList);

        gotoLoginFrame.setText("Logout");
        gotoLoginFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoLoginFrameMouseClicked(evt);
            }
        });
        menBar.add(gotoLoginFrame);

        gotoExpFrame.setText("Expense");
        gotoExpFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoExpFrameMouseClicked(evt);
            }
        });
        menBar.add(gotoExpFrame);

        gotoDashboard.setText("Dashboard");
        gotoDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoDashboardMouseClicked(evt);
            }
        });
        menBar.add(gotoDashboard);

        gotoMember.setText("Add Member");
        menBar.add(gotoMember);

        setJMenuBar(menBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memberTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(memberFormPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memberScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(memberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberFormPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(memberScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void memberNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_memberNameActionPerformed

    private void populateMembers(List<Member> memberList){
        MemberDao memDao = new MemberDao();
        memberList = memDao.getListOfMembers(this.group);
        StringBuilder strBuff = new StringBuilder("");
        for(Member member:memberList){
          strBuff.append("Name: "+member.getName()+",    Email: "+member.getEmail()+"; \n");
          strBuff.append(System.getProperty("line.separator"));
        }
        
        membersList.setText(strBuff.toString());
    }
    
    
    private void gotoLoginFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoLoginFrameMouseClicked

        System.out.println("Logout clicked");
        this.setVisible(false);
        setMessage(null);
        setGroupName(null);
        
        JFrame frame = new LoginFrame();
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_gotoLoginFrameMouseClicked

    private void gotoExpFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoExpFrameMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        System.out.println("Expense clicked");
        this.setVisible(false);
        
        
        JFrame frame = new Homeframe(group);
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_gotoExpFrameMouseClicked

    private void gotoDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoDashboardMouseClicked
        // TODO add your handling code here:
        System.out.println("Dashboard clicked");
        this.setVisible(false);
        JFrame frame = new DashboardFrame(group);
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_gotoDashboardMouseClicked

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
        // TODO add your handling code here:
        System.out.println("ADD MEMBER CLICKED");
        
        String name = memberName.getText();
        String email = memberEmail.getText();
        
        MemberDao memDao = new MemberDao();
        memDao.addMember(name, email, group);
        JFrame frame = new AddMemberFrame(group);
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_addMemberActionPerformed

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMemberFrame().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMember;
    private javax.swing.JMenu gotoDashboard;
    private javax.swing.JMenu gotoExpFrame;
    private javax.swing.JMenu gotoLoginFrame;
    private javax.swing.JMenu gotoMember;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField memberEmail;
    private javax.swing.JPanel memberFormPane;
    private javax.swing.JTextField memberName;
    private java.awt.ScrollPane memberScrollPane;
    private javax.swing.JPanel memberTitle;
    private java.awt.TextArea membersList;
    private javax.swing.JMenuBar menBar;
    private javax.swing.JLabel titleOfMember;
    // End of variables declaration//GEN-END:variables
}
