/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splitwise;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JFrame;
import splitwise.dao.ExpenseDao;
import splitwise.dao.MemberDao;

/**
 *
 * @author adityahandadi
 */
public class DashboardFrame extends MyFrame  {

    /**
     * Creates new form DashboardFrame
     */
    public String group;
    Map<String,Double> indivAmt;
    private List<Member> memberList3;
    
    public DashboardFrame() {
         super();
         initComponents();
    }

    
    public DashboardFrame(String group) {
         super();
         this.group = group;
        initComponents();
        
        memberList3 = new ArrayList();
        indivAmt = new HashMap();
        if(group!=null){
            populateIndividualExpense(group);
            populateMembers(memberList3);
        }
        else{
            System.out.println("NO GROUP NAME FOUND ERROR");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        memberTitle = new javax.swing.JPanel();
        titleOfMember = new javax.swing.JLabel();
        overallExpPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        summaryExpTable = new javax.swing.JTable();
        indivExpPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        individualExpTable = new javax.swing.JTable();
        indivExpSelectFormPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        memberNames = new javax.swing.JComboBox();
        findIndivExpenseBut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        memberNames1 = new javax.swing.JComboBox();
        menBar = new javax.swing.JMenuBar();
        gotoLoginFrame = new javax.swing.JMenu();
        gotoExpFrame = new javax.swing.JMenu();
        gotoDashboard = new javax.swing.JMenu();
        gotoMember = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleOfMember.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titleOfMember.setText("SPLITWISE - DASHBOARD");

        javax.swing.GroupLayout memberTitleLayout = new javax.swing.GroupLayout(memberTitle);
        memberTitle.setLayout(memberTitleLayout);
        memberTitleLayout.setHorizontalGroup(
            memberTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleOfMember)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        memberTitleLayout.setVerticalGroup(
            memberTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(memberTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleOfMember)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memberTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(memberTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Overall Expense Summary: ");

        summaryExpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Member Name", "Amount Owed"
            }
        ));
        jScrollPane1.setViewportView(summaryExpTable);

        jScrollPane2.setViewportView(jScrollPane1);

        javax.swing.GroupLayout overallExpPanelLayout = new javax.swing.GroupLayout(overallExpPanel);
        overallExpPanel.setLayout(overallExpPanelLayout);
        overallExpPanelLayout.setHorizontalGroup(
            overallExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overallExpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(overallExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overallExpPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        overallExpPanelLayout.setVerticalGroup(
            overallExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overallExpPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Individual Expense Summary: ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        individualExpTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MemberName", "Amount Owed", "Owed To", "Remark"
            }
        ));
        individualExpTable.setAutoscrolls(false);
        jScrollPane3.setViewportView(individualExpTable);

        scrollPane1.add(jScrollPane3);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Select Member:");

        memberNames.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        findIndivExpenseBut.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        findIndivExpenseBut.setText("GO");
        findIndivExpenseBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findIndivExpenseButActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Owing To:");

        memberNames1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout indivExpSelectFormPanelLayout = new javax.swing.GroupLayout(indivExpSelectFormPanel);
        indivExpSelectFormPanel.setLayout(indivExpSelectFormPanelLayout);
        indivExpSelectFormPanelLayout.setHorizontalGroup(
            indivExpSelectFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indivExpSelectFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(indivExpSelectFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indivExpSelectFormPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(memberNames, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(indivExpSelectFormPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(memberNames1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(findIndivExpenseBut)))
                .addContainerGap(347, Short.MAX_VALUE))
        );
        indivExpSelectFormPanelLayout.setVerticalGroup(
            indivExpSelectFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indivExpSelectFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(indivExpSelectFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(indivExpSelectFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memberNames1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(findIndivExpenseBut))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout indivExpPanelLayout = new javax.swing.GroupLayout(indivExpPanel);
        indivExpPanel.setLayout(indivExpPanelLayout);
        indivExpPanelLayout.setHorizontalGroup(
            indivExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indivExpPanelLayout.createSequentialGroup()
                .addGroup(indivExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(indivExpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(indivExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(indivExpSelectFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        indivExpPanelLayout.setVerticalGroup(
            indivExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indivExpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(indivExpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(indivExpPanelLayout.createSequentialGroup()
                        .addComponent(indivExpSelectFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        gotoLoginFrame.setText("Logout");
        gotoLoginFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoLoginFrameMouseClicked(evt);
            }
        });
        menBar.add(gotoLoginFrame);

        gotoExpFrame.setText("Expense");
        gotoExpFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoExpFrameMouseClicked(evt);
            }
        });
        menBar.add(gotoExpFrame);

        gotoDashboard.setText("Dashboard");
        menBar.add(gotoDashboard);

        gotoMember.setText("Add Member");
        gotoMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoMemberMouseClicked(evt);
            }
        });
        menBar.add(gotoMember);

        setJMenuBar(menBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(overallExpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(indivExpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(overallExpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indivExpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //For Dropdowns
    private void populateMembers(List<Member> memberList3){
        MemberDao memDao = new MemberDao();
        memberList3 = memDao.getListOfMembers(this.group);
        //StringBuilder strBuff = new StringBuilder("");
        String str[] = new String[memberList3.size()];
        int idx = 0;
        //str[idx++] = " ----- ";
        for(Member member:memberList3){
          str[idx] = member.getName();
          idx++;
        }
        
        memberNames.setModel(new javax.swing.DefaultComboBoxModel(str));
        memberNames1.setModel(new javax.swing.DefaultComboBoxModel(str));

    }
    
    //for upper sector displaying amount due in a group
    private void populateIndividualExpense(String group){
        
        MemberDao memberDao = new MemberDao();
        List<Member> memberlist = memberDao.getListOfMembers(group);
        //Final it should look like this
        String[][] indivExpArr = new String[memberlist.size()][2];

        int idx = 0;
        ExpenseDao expDao = new ExpenseDao();
        
        //For each member in memberList
        for(Member member:memberlist){
            //Find all spentByTotal by Member in group = room9
            Double spentByTot = expDao.getSpentByTot(group,member.getName());
            //Find all owedBy by same Member in group = room9
            Double owedBy = expDao.getOwedByTot(group,member.getName());
            //Amount due + or - would be owedBy - spentBy
            Double amountDue = owedBy - spentByTot;
            indivAmt.put(member.getName(),amountDue);
            //For each member split/share if owedBy = everyone equally
            
        }
        
        //Foreveryone, find expense from Dao for owedBy everyone.
        List<Expense> memberList2 = expDao.getListOfSplitAllMem(group);
        for(Expense exp:memberList2){
            Double totalAmount = exp.getAmount();
            Double indivShare = totalAmount/memberlist.size();
            
            //add indivShare to existing amount for everyone including individual Share of the paid
            Iterator<String> it = indivAmt.keySet().iterator();
            
            while(it.hasNext()){
                String key = it.next();
                Double amtDue = indivAmt.get(key);
                amtDue = amtDue + indivShare;
                indivAmt.put(key, amtDue);
                
            }
            
        }
        
        for(Member member:memberlist){
            //populate member and his amount due in String array which is fixed j = [0] & j = [1]
            Double amountDue = indivAmt.get(member.getName());
            indivExpArr[idx][0] = member.getName();
            indivExpArr[idx++][1] = new DecimalFormat("$0.00").format(amountDue);
        }

        summaryExpTable.setModel(new javax.swing.table.DefaultTableModel(
        indivExpArr,
        new String [] {
            "Member Name", "Amount Owed"
        }
        ));

        jScrollPane1.setViewportView(summaryExpTable);
        
    }
    
    private void gotoLoginFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoLoginFrameMouseClicked
        
        System.out.println("Logout clicked");
        this.setVisible(false);
        
        JFrame frame = new LoginFrame();
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_gotoLoginFrameMouseClicked

    private void gotoExpFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoExpFrameMouseClicked
        
        System.out.println("Expense Frame/Homeframe clicked");
        this.setVisible(false);
        
        JFrame frame = new Homeframe(group);
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_gotoExpFrameMouseClicked

    private void gotoMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoMemberMouseClicked
        
        System.out.println("AddMember clicked");
        this.setVisible(false);
        
        JFrame frame = new AddMemberFrame(group);
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_gotoMemberMouseClicked

    
    //Calculating the amount Due for Expenses only between members A & B
    private void findIndivExpenseButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findIndivExpenseButActionPerformed
        System.out.println("findIndivExpense Action Button Called");
        
        String paidBy = memberNames.getSelectedItem().toString();
        String owedBy = memberNames1.getSelectedItem().toString();
        
        
        ExpenseDao expenseDao = new ExpenseDao();
        
        //First finds all expense summary between A & B
        List<Expense> expList = expenseDao.getExpenseA_B(paidBy,owedBy,this.group);
        String[][] expArr = new String[expList.size()+1][4];
        int idx = 0;
        
        for(Expense exp:expList){
            expArr[idx][0] = exp.getSpentBy();
            expArr[idx][1] = new DecimalFormat("$0.00").format(exp.getAmount());
            expArr[idx][2] = exp.getSplitWith();
            if(exp.getAmount()<0){
                expArr[idx][3] =  exp.getSpentBy()+" Owes "+exp.getSplitWith();
            }
            else{
                expArr[idx][3] =  exp.getSplitWith()+" Owes "+exp.getSpentBy();
            } 
            
            idx++;
        }
        
        //calculate actual expense owed between two
        MemberDao memberDao = new MemberDao();
        List<Member> memberlist = memberDao.getListOfMembers(group);
        Double totalAmountDue = expenseDao.getAmountDue(paidBy,owedBy,this.group,memberlist.size());
        expArr[idx][0] = "Total";
        expArr[idx][1] = new DecimalFormat("$0.00").format(totalAmountDue);
        String compareAmt = new DecimalFormat("0.00").format(totalAmountDue);
        
        totalAmountDue = Double.parseDouble(compareAmt);
        if(totalAmountDue > 0.0){
            expArr[idx][3] = owedBy+" Owes "+paidBy;
        }
        else if(totalAmountDue < 0.0){
            expArr[idx][3] = paidBy+" Owes "+owedBy;
        }
        else{
            expArr[idx][3] = " Settled ";
        }
        
        
        individualExpTable = new javax.swing.JTable();

        individualExpTable.setModel(new javax.swing.table.DefaultTableModel(
            expArr,
            new String [] {
                "MemberName/Paid By", "Amount Owed", "Owed By", "Remark"
            }
        ));

        jScrollPane3.setViewportView(individualExpTable);
    }//GEN-LAST:event_findIndivExpenseButActionPerformed

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton findIndivExpenseBut;
    private javax.swing.JMenu gotoDashboard;
    private javax.swing.JMenu gotoExpFrame;
    private javax.swing.JMenu gotoLoginFrame;
    private javax.swing.JMenu gotoMember;
    private javax.swing.JPanel indivExpPanel;
    private javax.swing.JPanel indivExpSelectFormPanel;
    private javax.swing.JTable individualExpTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox memberNames;
    private javax.swing.JComboBox memberNames1;
    private javax.swing.JPanel memberTitle;
    private javax.swing.JMenuBar menBar;
    private javax.swing.JPanel overallExpPanel;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTable summaryExpTable;
    private javax.swing.JLabel titleOfMember;
    // End of variables declaration//GEN-END:variables
}
