/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splitwise;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import splitwise.dao.ExpenseDao;
import splitwise.dao.MemberDao;

/**
 *
 * @author Karthick/Aditya
 */
public class Homeframe extends MyFrame  {

    /**
     * Creates new form Homeframe
     */
    private List<Member> memberList;
    private List<Expense> expenseList;
    public String group;
    public Homeframe() {
         super();
         System.out.println("GroupName: "+super.groupName);
        initComponents();
    }
    
    public Homeframe(String group) {
         super();
         System.out.println("GroupName: "+group);
         this.group = group;
        initComponents();
        
        memberList = new ArrayList();
        
        if(group == null){
            System.out.println("No GroupName found ERROR");
        }
        else{
            //populate Members List
            populateMembers(memberList);
            populateExpense(expenseList);
        }
    }

    //populate Drop Downs
    private void populateMembers(List<Member> memberList){
        MemberDao memDao = new MemberDao();
        memberList = memDao.getListOfMembers(this.group);
        //StringBuilder strBuff = new StringBuilder("");
        String str[] = new String[memberList.size()+1];
        int idx = 0;
        //str[idx++] = " ----- ";
        for(Member member:memberList){
          str[idx] = member.getName();
          idx++;
        }
        
        spentByValDD.setModel(new javax.swing.DefaultComboBoxModel(str));
        str[idx] = "Everyone";
        
        //spentByValDD.setModel(new javax.swing.DefaultComboBoxModel(str));
        splitWithValDD.setModel(new javax.swing.DefaultComboBoxModel(str));

    }
    
    //populate TextField with existing expenses so far
    private void populateExpense(List<Expense> expenseList){
        ExpenseDao expDao = new ExpenseDao();
        expenseList = expDao.getListOfExpense(this.group);
        
        StringBuilder strBuff = new StringBuilder("");
        for(Expense expense:expenseList){
          strBuff.append(" "+expense.getSplitWith()+" Owes "+expense.getSpentBy()+" an Amount of $"+expense.getAmount());
          strBuff.append(System.getProperty("line.separator"));
        }
        
        allExpenses.setText(strBuff.toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        expenseFormPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        amount = new javax.swing.JTextField();
        spentByValDD = new javax.swing.JComboBox();
        splitWithValDD = new javax.swing.JComboBox();
        save = new javax.swing.JButton();
        splitType = new javax.swing.JComboBox();
        expenseScrollPane = new java.awt.ScrollPane();
        allExpenses = new java.awt.TextArea();
        menBar = new javax.swing.JMenuBar();
        gotoLoginFrame = new javax.swing.JMenu();
        gotoExpFrame = new javax.swing.JMenu();
        gotoDashboard = new javax.swing.JMenu();
        gotoMember = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("SPLITWISE - EXPENSE");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Spent By : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Split With: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Amount : ");

        spentByValDD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        splitWithValDD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        splitWithValDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                splitWithValDDActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        save.setText("Save Expense");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        splitType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Split", "Owe Full" }));

        javax.swing.GroupLayout expenseFormPanelLayout = new javax.swing.GroupLayout(expenseFormPanel);
        expenseFormPanel.setLayout(expenseFormPanelLayout);
        expenseFormPanelLayout.setHorizontalGroup(
            expenseFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expenseFormPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(expenseFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25)
                .addGroup(expenseFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(expenseFormPanelLayout.createSequentialGroup()
                        .addGroup(expenseFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spentByValDD, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(519, Short.MAX_VALUE))
                    .addGroup(expenseFormPanelLayout.createSequentialGroup()
                        .addComponent(splitWithValDD, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(splitType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(save)
                        .addGap(179, 179, 179))))
        );
        expenseFormPanelLayout.setVerticalGroup(
            expenseFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expenseFormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(expenseFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spentByValDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(expenseFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(expenseFormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(splitWithValDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save)
                    .addComponent(splitType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        expenseScrollPane.add(allExpenses);

        gotoLoginFrame.setText("Logout");
        gotoLoginFrame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoLoginFrameMouseClicked(evt);
            }
        });
        gotoLoginFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotoLoginFrameActionPerformed(evt);
            }
        });

        gotoLoginFrame.addActionListener(new java.awt.event.ActionListener() {
            @Override public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFrame frame = new LoginFrame();
                frame.setTitle("SplitWise");
                frame.setVisible(true);
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        });

        menBar.add(gotoLoginFrame);

        gotoExpFrame.setText("Expense");
        menBar.add(gotoExpFrame);

        gotoDashboard.setText("Dashboard");
        gotoDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoDashboardMouseClicked(evt);
            }
        });
        menBar.add(gotoDashboard);

        gotoMember.setText("Add Member");
        gotoMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotoMemberMouseClicked(evt);
            }
        });
        menBar.add(gotoMember);

        setJMenuBar(menBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expenseScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(expenseFormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expenseFormPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(expenseScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gotoLoginFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotoLoginFrameActionPerformed
        
    }//GEN-LAST:event_gotoLoginFrameActionPerformed

    private void gotoLoginFrameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoLoginFrameMouseClicked
        // TODO add your handling code here:
        System.out.println("Logout clicked");
        this.setVisible(false);
        
        JFrame frame = new LoginFrame();
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_gotoLoginFrameMouseClicked

    private void gotoDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoDashboardMouseClicked
        // TODO add your handling code here:
         System.out.println("Dashboard clicked");
         this.setVisible(false);
         
        JFrame frame = new DashboardFrame(this.group);
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_gotoDashboardMouseClicked

    private void gotoMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotoMemberMouseClicked

        // TODO add your handling code here:
         System.out.println("Add Member clicked");
         this.setVisible(false);
         
        JFrame frame = new AddMemberFrame(group);
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_gotoMemberMouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        System.out.println("Homeframe Save ActionPerformed");
        Expense expense = new Expense();
        expense.setGroupName(this.group);
        expense.setSpentBy(spentByValDD.getSelectedItem().toString());
        Double amount_ = Double.parseDouble(amount.getText());
        
        String splitType_ = splitType.getSelectedItem().toString();
        
        expense.setSplitWith(splitWithValDD.getSelectedItem().toString());
        
        if(splitType_.equals("Split") && !expense.getSplitWith().equals("Everyone")){
            amount_ = amount_/2;
            expense.setAmount(amount_); //new DecimalFormat("$0.00").format(amount)
        }
        else{
            expense.setAmount(amount_);
        }
        
        
        
        ExpenseDao expenseDao = new ExpenseDao();
        expenseDao.addExpense(expense.getSpentBy(), expense.getAmount(), expense.getSplitWith(), group);
        
        JFrame frame = new Homeframe(group);
        frame.setTitle("SplitWise");
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_saveActionPerformed

    private void splitWithValDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_splitWithValDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_splitWithValDDActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homeframe().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea allExpenses;
    private javax.swing.JTextField amount;
    private javax.swing.JPanel expenseFormPanel;
    private java.awt.ScrollPane expenseScrollPane;
    private javax.swing.JMenu gotoDashboard;
    private javax.swing.JMenu gotoExpFrame;
    private javax.swing.JMenu gotoLoginFrame;
    private javax.swing.JMenu gotoMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menBar;
    private javax.swing.JButton save;
    private javax.swing.JComboBox spentByValDD;
    private javax.swing.JComboBox splitType;
    private javax.swing.JComboBox splitWithValDD;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables
}
