/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package splitwise;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import splitwise.dao.RegLogdao;

/**
 *
 * @author Karthick/Aditya
 */
public class LoginFrame extends MyFrame {

    /**
     * Creates new form LoginFrame
     */
    
    public static JFrame defFtame;
    public String group;
    
    public LoginFrame() {
         super();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        sectionPanel = new javax.swing.JPanel();
        registerPanel = new javax.swing.JPanel();
        registersubpanel = new javax.swing.JPanel();
        register = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextfield = new javax.swing.JTextField();
        Unamelabel = new javax.swing.JLabel();
        userTextfield = new javax.swing.JTextField();
        Rpasslabel = new javax.swing.JLabel();
        Rpasstextfield = new javax.swing.JTextField();
        Rbutton = new javax.swing.JButton();
        rmessage = new javax.swing.JTextField();
        loginPanel = new javax.swing.JPanel();
        loginsubpanel = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        loginusername = new javax.swing.JLabel();
        Lusertext = new javax.swing.JTextField();
        loginPass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        Lbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(894, 365));

        mainPanel.setLayout(new java.awt.BorderLayout());

        title.setBackground(new java.awt.Color(51, 255, 51));
        title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("SPLITWISE");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        title.setMaximumSize(new java.awt.Dimension(368, 25));
        title.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        mainPanel.add(title, java.awt.BorderLayout.NORTH);

        sectionPanel.setLayout(new java.awt.GridLayout(1, 2));

        registerPanel.setLayout(new java.awt.BorderLayout());

        registersubpanel.setBackground(new java.awt.Color(204, 204, 204));
        registersubpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        registersubpanel.setLayout(new java.awt.GridLayout(9, 1));

        register.setBackground(new java.awt.Color(204, 204, 255));
        register.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        register.setForeground(new java.awt.Color(0, 0, 51));
        register.setText("                                            REGISTER");
        registersubpanel.add(register);

        nameLabel.setText(" Full Name:");
        registersubpanel.add(nameLabel);

        nameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextfieldActionPerformed(evt);
            }
        });
        registersubpanel.add(nameTextfield);

        Unamelabel.setText(" User Name");
        registersubpanel.add(Unamelabel);
        registersubpanel.add(userTextfield);

        Rpasslabel.setText(" Password:");
        registersubpanel.add(Rpasslabel);
        registersubpanel.add(Rpasstextfield);

        Rbutton.setText("Register");
        Rbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbuttonActionPerformed(evt);
            }
        });
        registersubpanel.add(Rbutton);
        registersubpanel.add(rmessage);

        registerPanel.add(registersubpanel, java.awt.BorderLayout.CENTER);

        sectionPanel.add(registerPanel);

        loginPanel.setLayout(new java.awt.BorderLayout());

        loginsubpanel.setBackground(new java.awt.Color(204, 204, 204));
        loginsubpanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));
        loginsubpanel.setLayout(new java.awt.GridLayout(6, 1));

        login.setBackground(new java.awt.Color(153, 153, 255));
        login.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        login.setForeground(new java.awt.Color(51, 0, 51));
        login.setText("                                            LOGIN    ");
        loginsubpanel.add(login);

        loginusername.setText("   User Name:");
        loginsubpanel.add(loginusername);

        Lusertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LusertextActionPerformed(evt);
            }
        });
        loginsubpanel.add(Lusertext);

        loginPass.setText("  Password :");
        loginsubpanel.add(loginPass);
        loginsubpanel.add(jPasswordField1);

        Lbutton.setText("Login");
        Lbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbuttonActionPerformed(evt);
            }
        });
        loginsubpanel.add(Lbutton);

        loginPanel.add(loginsubpanel, java.awt.BorderLayout.CENTER);

        sectionPanel.add(loginPanel);

        mainPanel.add(sectionPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextfieldActionPerformed

    //Register Button Action Event
    private void RbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbuttonActionPerformed
        // TODO add your handling code here:
        String fname= nameTextfield.getText();
        String uname = userTextfield.getText() ;
        String upass=  Rpasstextfield.getText();
        
        User user = new User();
        user.setFullName(fname);
        user.setUserName(uname);
        user.setPassword(upass);
        
        // call dao
        System.out.println("Registering USer");
        RegLogdao reglogDao = new RegLogdao();
        String status = reglogDao.registerRecord(user);
        
        setMessage(status);
        rmessage.setText(status);
        System.out.println(status);
        //Populate JTextField with this message
        
    }//GEN-LAST:event_RbuttonActionPerformed

    private void LusertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LusertextActionPerformed
        
    }//GEN-LAST:event_LusertextActionPerformed

    //Login Button event
    private void LbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbuttonActionPerformed
        // TODO add your handling code here:
        String uname = Lusertext.getText() ;
        String upass=  jPasswordField1.getText();
        
        User user = new User();
        user.setUserName(uname);
        user.setPassword(upass);
        // call dao
        RegLogdao reglogDao = new RegLogdao();
        String status = reglogDao.authenticate(user);
        System.out.println("UNAME "+uname);
        
        if(status.equals("success")){
            System.out.println("Login is success");
            
            super.groupName = uname;
            defFtame = new Homeframe(uname);
            
            //JFrame hframe= new Homeframe();
            defFtame.setTitle("SplitWise Home");
            defFtame.setVisible(true);
            
        }
        else{
            //do Nothing
            //populate Message on JTextField
            infoBox("login failed", "Alert message");
            defFtame = new LoginFrame();
            //JFrame hframe= new Homeframe();
            defFtame.setTitle("SplitWise Home");
            defFtame.setVisible(true);
            
            System.out.println("This called");
            setMessage("Login Failed");
        }
        
        dispose();
    }//GEN-LAST:event_LbuttonActionPerformed
public  void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * @param args the command line arguments
     */
     /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                defFtame = new LoginFrame();
                defFtame.setVisible(true);
                
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Lbutton;
    private javax.swing.JTextField Lusertext;
    private javax.swing.JButton Rbutton;
    private javax.swing.JLabel Rpasslabel;
    private javax.swing.JTextField Rpasstextfield;
    private javax.swing.JLabel Unamelabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel login;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel loginPass;
    private javax.swing.JPanel loginsubpanel;
    private javax.swing.JLabel loginusername;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextfield;
    private javax.swing.JLabel register;
    private javax.swing.JPanel registerPanel;
    private javax.swing.JPanel registersubpanel;
    private javax.swing.JTextField rmessage;
    private javax.swing.JPanel sectionPanel;
    private javax.swing.JLabel title;
    private javax.swing.JTextField userTextfield;
    // End of variables declaration//GEN-END:variables
}
